# -*- coding: utf-8 -*-
"""MSSF_Module.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1do96xbYznOqDu4R_LRTRMHbF84oRyiJw
"""

import torch
import torch.nn as nn


class AMSFuse(nn.Module):
    def __init__(self, in_channels, out_channels, reduction=16):
        super(AMSFuse, self).__init__()

        self.in_channels = in_channels
        self.out_channels = out_channels
        self.reduction = reduction
        self.num_branches = 3

        # Branch 1: Standard 3x3 Conv
        self.branch1 = self._conv_block(
            in_channels, out_channels, kernel_size=3, padding=1
        )

        # Branch 2: Asymmetric Conv (1x5 + 5x1)
        self.branch2 = nn.Sequential(
            nn.Conv2d(in_channels, out_channels, kernel_size=(1, 5),
                      padding=(0, 2), bias=False),
            nn.BatchNorm2d(out_channels),
            nn.GELU(),

            nn.Conv2d(out_channels, out_channels, kernel_size=(5, 1),
                      padding=(2, 0), bias=False),
            nn.BatchNorm2d(out_channels),
            nn.GELU()
        )

        # Branch 3: Dilated Conv (2 → 3)
        self.branch3 = nn.Sequential(
            nn.Conv2d(in_channels, out_channels, kernel_size=3,
                      padding=2, dilation=2, bias=False),
            nn.BatchNorm2d(out_channels),
            nn.GELU(),

            nn.Conv2d(out_channels, out_channels, kernel_size=3,
                      padding=3, dilation=3, bias=False),
            nn.BatchNorm2d(out_channels),
            nn.GELU()
        )

        # Learnable branch scaling
        self.scale_weights = nn.Parameter(torch.ones(self.num_branches))

        # Channel attention gate
        total_channels = out_channels * self.num_branches
        self.channel_gate = nn.Sequential(
            nn.AdaptiveAvgPool2d(1),
            nn.Conv2d(total_channels, total_channels // reduction, kernel_size=1),
            nn.ReLU(inplace=True),
            nn.Conv2d(total_channels // reduction, total_channels, kernel_size=1),
            nn.Sigmoid()
        )

        # Fusion projection
        self.fusion_conv = self._conv_block(
            total_channels, out_channels, kernel_size=1, padding=0
        )

        # Residual path
        if in_channels != out_channels:
            self.residual = nn.Conv2d(
                in_channels, out_channels, kernel_size=1, bias=False
            )
        else:
            self.residual = nn.Identity()

        self._initialize_weights()

    def _conv_block(self, in_ch, out_ch, kernel_size, padding):
        return nn.Sequential(
            nn.Conv2d(in_ch, out_ch, kernel_size,
                      padding=padding, bias=False),
            nn.BatchNorm2d(out_ch),
            nn.GELU()
        )

    def _initialize_weights(self):
        for m in self.modules():
            if isinstance(m, nn.Conv2d):
                nn.init.kaiming_normal_(
                    m.weight, mode='fan_out', nonlinearity='relu'
                )
                if m.bias is not None:
                    nn.init.zeros_(m.bias)

            elif isinstance(m, nn.BatchNorm2d):
                nn.init.constant_(m.weight, 1)
                nn.init.constant_(m.bias, 0)

    def forward(self, x):
        residual = self.residual(x)

        b1 = self.branch1(x)
        b2 = self.branch2(x)
        b3 = self.branch3(x)

        branches = [b1, b2, b3]

        # Softmax branch weighting
        scale_weights = torch.softmax(self.scale_weights, dim=0)
        scaled = [
            scale_weights[i] * branch
            for i, branch in enumerate(branches)
        ]

        fused = torch.cat(scaled, dim=1)

        # Channel recalibration
        attention = self.channel_gate(fused)
        fused = fused * attention

        # Final fusion
        out = self.fusion_conv(fused)

        # Residual connection
        out = out + residual

        return out